# Base configs
baseurl: ""
url: "https://tamascsaba.github.io/forras12/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "V치rpalota Forr치s utca 12"
subtitle: "V치rpalota Forr치s utca 12"
author: ""
bio: ""
publicise: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
